version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=frontend.settings
    depends_on:
      - auth-service
      - video-service

  video-service:
    build:
      context: ./video-service
    container_name: video-service
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=video_service.settings
